format = '''
[](fg:color1)$os$username[ ](fg:color1 bg:color4)$directory[ ](fg:color4)$git_branch$git_status$rust$python
$character'''
right_format = '''
$time
'''
add_newline = false
palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '#eeb4ea'
color2 = '#4a204c'
color3 = '#d0c3cc'
color4 = '#241e23'
color5 = '#4a204c'
color6 = '#171216'
color7 = '#171216'
color8 = '#eeb4ea'
color9 = '#f6b8ab'

# Prompt symbols 
[character]
success_symbol = "[](color9 bold)"
error_symbol = "[](@{error})"
vicmd_symbol = "[](#f9e2af)"
[os]
disabled = false
style = "bg:color1 fg:color2"
[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "
NixOS = " "
[username]
style_user = 'bg:color1 fg:color2'
style_root = 'bg:color1 fg:color2'
format = '[$user]($style)'
show_always = true
[directory]
format = "[$path ](fg:color3 bg:color4)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
"Workspace" = " "

[git_branch]
format = "[](fg:color8)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[](fg:color4)"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
staged = "+${count}"
stashed = "*${count}"
format = "[](fg:color4)[(bg:color8 fg:color5) $all_status$ahead_behind](fg:color3 bg:color4)[](fg:color4) "

[time]
format = "[](fg:color8)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format

[python]
format = "[](fg:color8)[${symbol}${version}](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[](fg:color4) "
symbol = ' '
# pyenv_version_name = true
pyenv_prefix = 'venv'

[rust]
symbol = ' '
format = "[](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[](fg:color4) "
